export const ticketHeaders = [
	{label: "Ticket Title", key: "ticket_form"},
	{label: "Ticket type", key: "ticket_type"},
	{label: "Status", key: "status"},
	{label: "Point of contact name", key: "point_of_contact_name"},
	{label: "Point of contact number", key: "point_of_contact_phone_number"},
	{label: "Point of contact address", key: "point_of_contact_address"},
	{label: "Number of technicians", key: "number_of_technicians"},
	{label: "Number of work station", key: "number_of_work_station"},
	{label: "Number of work system", key: "number_of_work_systems"},
	{label: "Scope of work", key: "scope_of_work_description"},
	{label: "Scope of work document", key: "scope_of_work_document"},
	{label: "Date created", key: "created_at"},
	{label: "Start date", key: "start_date_time"},
	{label: "End date", key: "end_date_time"},
	{label: "Material Procurements", key: "materials_description"},
	{label: "Software installation name", key: "software_installation_name"},
	{label: "software installation quantity", key: "software_installation_quantity"},
	{label: "Software customization name", key: "software_customization_name"},
	{label: "software customization quantity", key: "software_customization_quantity"},
	{label: "Hardware name", key: "hardware_name"},
	{label: "Hardware quantity", key: "hardware_quantity"},
	{label: "Hardware component(s) type list", key: "hardware_component_type_list"},
	{label: "Hardware component(s) type quantity", key: "hardware_component_type_quantity"},
	{label: "Locations", key: "locations"},
	{label: "Pick Location", key: "pick_locations"},
	{label: "Drop Off Locations", key: "drop_off_locations"},
];

export const customerHeaders = [
    { label: "Company name", key: "company_name" },
    { label: "First name", key: "first_name" },
    { label: "Last name", key: "last_name" },
    { label: "Company representative email", key: "email" },
    { label: "Company finance email", key: "company_finance_email" },
    { label: "Company email", key: "company_name" },
    { label: "Status", key: "status" },
    { label: "Date Created", key: "datetime" },
];
